apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qcloud-vote-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qcloud-vote-back
    spec:
      containers:
      - name: qcloud-vote-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: qcloud-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: qcloud-vote-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qcloud-vote-front
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: qcloud-vote-front
    spec:
      containers:
      - name: qcloud-vote-front
        image: hub.tencentyun.com/geffzhang/qcloud-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "qcloud-vote-back"
      imagePullSecrets:
       - name: qcloudregistrykey
       - name: tencenthubkey
---
apiVersion: v1
kind: Service
metadata:
  name: qcloud-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: qcloud-vote-front